before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

universal_binaries:
  - replace: true

dockers:
  - image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:latest-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
      - "--build-arg=GO_PROJECT_NAME={{ .ProjectName }}"
    extra_files:
      - docker-entrypoint.sh

docker_manifests:
  - name_template: "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-amd64"

  - name_template: "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}-amd64"

  - name_template: "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"

  - name_template: "ghcr.io/korylprince/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-amd64"
